spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 169570536200-uvd79dr0f5l1r2akbeburkj8j8k90266.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
          naver:
            client-id: pkeT1523qtpMPXopI8Jd
            client-secret: NCP7NLKmgr
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: name,email,profile_image
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response