spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wineoclock?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC # DB Source URL
    username: root # DB username
    password: 1qazxsw2 # DB password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        show_sql: true

    show-sql: true

    hibernate:
      ddl-auto: create-drop

      naming:
        implicit-strategy=org:
          hibernate:
            boot:
              model:
                naming:
                  ImplicitNamingStrategyLegacyJpaImpl:
                  PhysicalNamingStrategyStandardImpl:

  profiles:
    include: jwt, oauth

  session:
    store-type: jdbc

#spring.session.jdbc.initialize-schema=always spring.session.jdbc.schema=classpath:org/springframework/session/jdbc/schema-mysql.sql
