spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wineoclock?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC # DB Source URL
    username: root # DB username
    password: 1qazxsw2 # DB password

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update

      naming:
        implicit-strategy=org:
          hibernate:
            boot:
              model:
                naming:
                  ImplicitNamingStrategyLegacyJpaImpl:
                  PhysicalNamingStrategyStandardImpl:
  security:
    jwt:
      header: Authorization
      secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
      token-validity-in-seconds: 86400

  profiles:
    include: jwt, oauth

  session:
    store-type: jdbc

#spring.session.jdbc.initialize-schema=always spring.session.jdbc.schema=classpath:org/springframework/session/jdbc/schema-mysql.sql
